language: node_js

node_js:
    - stable

before_install:
    - cd Absurdly.JS/

install:
    - npm install

script:
    - npm run cover

after_script:
    - 'cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js'
